export const BLANK: string = "blank";
export const ORDER_COMPLETE: string = "order-complete";
export const ORDER_COMPLETE_ABBREVIATED = "order-complete-abbreviated";
export const ERROR: string = "error";
export const ERROR_START_AGAIN: string = "error-start-again";
export const ERROR_NOT_FOUND: string = "error-not-found";
export const BASKET: string = "basket";
export const DELIVERY_DETAILS: string = "delivery-details";
export const EMAIL_OPTIONS: string = "email-options";
